### ISSUE TITLE
Create crown position dataset

### ISSUE THREAD

**Issue by gonzalezeb** [SCBI-ForestGEO/SCBI-ForestGEO-Data#1]
Please @mcgregorian1  create a datasheet that contains all trees for which crown position will be recorded (only live trees):
-dendroband biannual list 
-cored trees

The list should have the basic tree data (tag, stem tag, bla, bla, bla... cored-yes/no, dbh 2018-this can be populated later)

Amanda will enter data here and she can prep a fieldform for later getting cored trees data in the field.

Si?

**Comment by mcgregorian1** [comment]
I've made this form (called scbi.crownposition) in the crown position folder. Let me know if you'd like it to be different.

**Comment by teixeirak** [comment]
Thanks @mcgregorian1, looks fantastic overall. Could you please add DBH in 2008 and 2013 (for help with field ID and to facilitate analyses)?

Also, we may end up wanting to add some smaller trees if time permits.  We'll assess pace and then decide.

**Comment by mcgregorian1** [comment]
Sure thing. I can get to this tomorrow.

**Comment by mcgregorian1** [comment]
The dbh has been added. Let me know if you'd like anything else changed

**Comment by teixeirak** [comment]
That's good for now. Why do some of the DBH values have so many decimal points?

**Comment by mcgregorian1** [comment]
Just realized I hadn't responded to this. That was a holdover from an earlier formatting. I've since fixed the code to only show to the first decimal

**Comment by teixeirak** [comment]
Were these calculated based on dendro bands?

**Comment by mcgregorian1** [comment]
Possibly? That makes sense. I hadn't noticed the numerous decimal points until I had started working with the files in R.

**Comment by mcgregorian1** [comment]
For the record (in this issue), the form I made originally called "scbi.crownposition" has been merged and, and the contents are now in dendro_cored_full in the [tree_crowns](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_dimensions/tree_crowns) repo.
