### ISSUE TITLE
Wrong quadrats/coordinates in ForestGEO data

### ISSUE THREAD

**Issue by mcgregorian1** [SCBI-ForestGEO/SCBI-ForestGEO-Data#11]
@teixeirak @gonzalezeb 

When calculating the local coordinates (lx and ly) for 2013 and 2008, I noticed that I was getting negative values and values >20. The only way this would happen is if either the quadrat for a particular stem is wrong, or the coordinates themselves are wrong.

For example, I have tag 130965 (quadrat 1306) whose lx and ly are 19.2 and -6.8, respectively. Having a negative ly tells me that either the gy is wrong (for quadrat 1306 gy values should be between 100-120; it is listed as 93.2), or the quadrat is wrong (if so, the quadrat should be 1305).

I've checked with @ValentineHerr about this and the 2018 data also has issues.

The issues in 2008 are the same in 2013, and some additions are from 2018. A csv file with the mistakes (and the lx and ly values) can be found [here](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_main_census/data/temp_coordinate_issues/combined_years.csv).
- I've put the Rscript in the same folder; I wasn't sure if we wanted to put it in the Rscripts folder since while this is a temp issue, the script outline can be used to double check future ForestGEO datasets.

**Comment by gonzalezeb** [comment]
Thanks Ian. By doing a quick check it seems that those are mostly quadrat errors. I will check those records and give corrections to Suzanne.

**Comment by mcgregorian1** [comment]
There are two more issues with tags in the 2018 data:

1. There is a tag 1437923 (all tags should be at max 6 characters). It is a libe in 1403.
2. 93965 is labeled as both qupr and acne (for the acne, its stemtag is NA).

**Comment by gonzalezeb** [comment]
Both records already checked and sent to eliminate. So you can erase them in the temporal 2018 data.
