### ISSUE TITLE
Elevation data of SCBI at 5m x 5m spatial scale

### ISSUE THREAD

**Issue by DanielZuleta** [SCBI-ForestGEO/SCBI-ForestGEO-Data#16]
Dear PI's and plot managers,
@gonzalezeb , @teixeirak 

I am running an analysis with this plot that requires the elevation data at the 5m x 5m spatial scales. However, in your repository, I have only found the data at the 20m x 20m scale. 
Do you have this data at finer spatial scale?

Thanks,
Daniel Zuleta

**Comment by teixeirak** [comment]
At least in theory, we should be able to use NEON data (1x1m):
- [elevation](https://data.neonscience.org/data-product-view?dpCode=DP3.30024.001)
- [slope & aspect](https://data.neonscience.org/data-product-view?dpCode=DP3.30025.001)

The plot was flown in summers of 2016 and 2017.

I have never looked at the data.

**Comment by teixeirak** [comment]
[This link](https://data.neonscience.org/browse-data?showAllDates=true&dpCode=DP3.30024.001&siteCode=PRIN&siteCode=WOOD&siteCode=TALL&siteCode=ARIK&siteCode=JERC&siteCode=OSBS&siteCode=DEJU&siteCode=KONZ&siteCode=MLBS&siteCode=WREF&siteCode=HOPB&siteCode=RMNP&siteCode=BARR&siteCode=GRSM&siteCode=OAES&siteCode=SERC&siteCode=YELL&siteCode=ABBY&siteCode=DELA&siteCode=SOAP&siteCode=GUIL&siteCode=SCBI&siteCode=DSNY&siteCode=GUAN&siteCode=TOOL&siteCode=MCDI&siteCode=ORNL&siteCode=UKFS&siteCode=CPER&siteCode=HEAL&siteCode=NOGP&siteCode=LAJA&siteCode=WLOU&siteCode=REDB&siteCode=LENO&siteCode=LIRO&siteCode=HARV&siteCode=BONA&siteCode=BART&siteCode=SJER&siteCode=STEI&siteCode=JORN&siteCode=MOAB&siteCode=STER&siteCode=BLAN&siteCode=SRER&siteCode=ONAQ&siteCode=CLBJ&siteCode=NIWO&siteCode=PUUM&siteCode=CUPE&siteCode=TEAK&siteCode=UNDE) should take you to the page where you can select the files that you want. I'm not sure what you'd need.

**Comment by mcgregorian1** [comment]
Hi @DanielZuleta 

We were working on elevation data today and I think we have a code that can help you. It is the script called [topo_wet_index](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/R_scripts/topo_wet_index.R), and involves manipulating rasters to different dimensions. I suggest running # 1-5 to see the output, then you should be able to alter resolutions and write out a .tif file that can be used in ArcGIS.

Please let me know if you have any questions.

Here is the output of # 1-5.
![image](https://user-images.githubusercontent.com/39522449/61155585-47186280-a4bf-11e9-9eab-3d84da545618.png)

**Comment by teixeirak** [comment]
Thanks, @mcgregorian1 !
