### ISSUE TITLE
Add TWI and elevation .tif files to this repo

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-ForestGEO-Data#17]
@mcgregorian1, I may be missing them, but I don't see the TWI and elevation .tif files that you created (see issue #16) in this repo. Could you please load them here (with brief description)?

**Comment by mcgregorian1** [comment]
@teixeirak I had put them in the [elevation](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/spatial_data/elevation) folder and briefly documented them in the README for that folder.

**Comment by teixeirak** [comment]
Thanks!
