### ISSUE TITLE
tree mortality: code some basic summary charts

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-ForestGEO-Data#18]
@alyssaterrell , @ValentineHerr ,

It would be helpful to write scripts to make some charts summarizing results of the mortality census, similar to the ones we used to produce: mortality rate and biomass mortality for each census-- total and by genera, and some additional ones breaking up by genera for Fraxinus and Quercus.  It would also be nice to include an update of the one in the Shenandoah paper.

The main purpose is to keep us up to date with the results of the census/ allow us to pick out any interesting new patterns. It's also handy to have nice graphs ready for presentations, tours, etc.  

This is not particularly urgent, but if its ready tomorrow I'd use them for the VNPS tour (replacing some ugly ones I threw together quickly).

**Comment by ValentineHerr** [comment]
Working on reproducing this now:

![image](https://user-images.githubusercontent.com/19673377/65775740-c0167600-e10e-11e9-9986-9f2b9fefdaec.png)


@teixeirak,
For mortality rates, If I subset for species and censuses that started with > 100 individuals I have a similar results but if I subset for species that always had N>100 to start with (at each census), Ulru disappears ( Ulru went below 100 individuals at the end of 15-16 census and that is why we don't see anything for those years in the plot above). 
Any preference on how to handle that ?

**Comment by ValentineHerr** [comment]
@teixeirak, to clarify,

Two options: 
A - we ignore mortality rates for one census because there was not n >100 a the beginning of that census,  but we still plot the other censuses for that species. It would look like this:

![image](https://user-images.githubusercontent.com/19673377/65778309-b2172400-e113-11e9-9800-927707d7c001.png)


B- We ignore the species all together is one of the census did not have n>100. It would look like this:
![image](https://user-images.githubusercontent.com/19673377/65778374-cf4bf280-e113-11e9-8df0-eb0f00cf7413.png)

**Comment by teixeirak** [comment]
> @teixeirak,
> For mortality rates, If I subset for species and censuses that started with > 100 individuals I have a similar results but if I subset for species that always had N>100 to start with (at each census), Ulru disappears ( Ulru went below 100 individuals at the end of 15-16 census and that is why we don't see anything for those years in the plot above).
> Any preference on how to handle that ?

Let's include ULRU (species with ≥100 individuals at start)

**Comment by teixeirak** [comment]
Let's go with option A

**Comment by teixeirak** [comment]
The plots look very nice, by the way. Thank you!

**Comment by ValentineHerr** [comment]
Ok I'll push them.

working on updating Shenandoah results now.

**Comment by teixeirak** [comment]
Let's put the Shenandoah results in this repo, not the Shen repo. I'm not currently planning to update the figure/ stats in that paper.

**Comment by ValentineHerr** [comment]
Hmm... That could get tricky....

What figures would you like here? I believe this is the only one that does not use Shenandoah data: 
 
![image](https://user-images.githubusercontent.com/19673377/65779760-6154fa80-e116-11e9-9d0a-9aa829b44775.png)

**Comment by teixeirak** [comment]
That's the only one I had in mind

**Comment by ValentineHerr** [comment]
Ok, I'll try to script it here again so that the two repos do not depend on each other.

**Comment by ValentineHerr** [comment]
@teixeirak, it would actually be hard/take a lot of time without updating the Shenandoah repo... I'll try to work there, on a separate branch.

**Comment by teixeirak** [comment]
It's not that important. You can just drop that one. The point was just to make some quick figures to visualize some results from the census. Since we don't have any specific use in mind right now, its not worth extra effort for this one.

**Comment by ValentineHerr** [comment]
ok

**Comment by ValentineHerr** [comment]
In the end the script ran over lunch time and [here ](https://github.com/EcoClimLab/Shenandoah/blob/Shanandoah_with_2019_SCBI_data/results/figures/for_manuscript/Figure%204.tif)is the figure:

![image](https://user-images.githubusercontent.com/19673377/65788265-b0a42680-e128-11e9-9906-52ced7f5955b.png)


NOTE: Cercis went below 100 individuals after 2018.

**Comment by teixeirak** [comment]
Thanks! Which is the taxa that got up to ~7% mort rate in 2019?

**Comment by ValentineHerr** [comment]
Carpinus

**Comment by teixeirak** [comment]
Thanks!

@alyssaterrell , (@gonzalezeb) , any idea what's getting Carpinus?

**Comment by gonzalezeb** [comment]
It seems that nothing in particular gets them. Canker but not a particular pest or pathogen known.

https://edis.ifas.ufl.edu/st120

Sent from my iPhone

On Sep 27, 2019, at 8:22 PM, Kristina Anderson-Teixeira <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION:This email originated outside the Institution. Unless you recognize the sender and know the content is safe, do not follow guidance, click links, or open attachments.

Thanks!

@alyssaterrell<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falyssaterrell&data=02%7C01%7Cgonzalezeb%40si.edu%7Ca498d376794a451d588508d74377ae9d%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637052053618945035&sdata=Hmswhblb2GYRNH%2F01hLQGIskbQRDN571xx3AM%2F%2FFzJ4%3D&reserved=0> , (@gonzalezeb<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgonzalezeb&data=02%7C01%7Cgonzalezeb%40si.edu%7Ca498d376794a451d588508d74377ae9d%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637052053618955024&sdata=vGuZfUetCF3%2FxaW5OS4KVNHFxNFoqiMe5iasla26gqg%3D&reserved=0>) , any idea what's getting Carpinus?
