### ISSUE TITLE
Chionanthus virginicus excluded in mort 2019

### ISSUE THREAD

**Issue by gonzalezeb** [SCBI-ForestGEO/SCBI-ForestGEO-Data#21]
I am just noticing that _Chionanthus virginicus_ (fringe tres) was excluded in the 2019 mortalitu census. We included the species in the mort 2018 survey as a potential host to EAB, and in fact, we found evidence f sign on few stems. 
@teixeirak 
Do you remember if we specifically said that species should be excluded in last year census? Why?

**Comment by teixeirak** [comment]
We definitely want it included; I think it must have been excluded by error.  (All stems are <10cm, correct?) Let's be sure too get it this year.
