### ISSUE TITLE
move bark depth data to here?

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBI-ForestGEO-Data#22]
It would be convenient to have [SCBI_bark_depth.csv](https://github.com/SCBI-ForestGEO/McGregor_climate-sensitivity-variation/blob/master/data/traits/SCBI_bark_depth.csv) file here to be able to source it into R. Currently, I can source it from where it is (private repo for Ian's analysis) but there is a TOKEN that needs to be updated on a regular basis so the code doesn't always run.

**Comment by teixeirak** [comment]
Done.

**Comment by ValentineHerr** [comment]
thanks!
