### ISSUE TITLE
review status at coring

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBI-ForestGEO-Data#23]
Currently, [tree_cores/cross-dated_cores_CSVformat/all_core_chronologies.csv](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/cross-dated_cores_CSVformat/all_core_chronologies.csv), which is created by [tree_cores/R-script/Standardize_rwl_to_csv.R](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/R-script/Standardize_rwl_to_csv.R) has column 'status.at.coring' that is 'alive' if the tree tag appears in [tree_cores/measurement_files/measurement_notes_2010_chronology.csv](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/measurement_files/measurement_notes_2010_chronology.csv) and 'dead' otherwise (if it appears in [tree_cores/measurement_files/measurement_notes_2016_17_chronology.csv](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/measurement_files/measurement_notes_2016_17_chronology.csv))

### First issue: 29 tags appear in both measurement files.
In theory when a tree was cored a second time in 2016-17, that later core was used instead of the 2010 core. That means that those 29 tags should get a 'dead' status.at.coring instead of 'alive'.

In practice, 17 out of those 29 trees seem to have sopped before 2011 (sometimes much earlier) and 12 actually have data passed 2011. So it is unclear if those 17 trees should get 'dead' as the cores kept might well have been the 2010 core. Regardless, since we are removing the 10 years prior to death, we should probably change all those status to dead. Since the tags appear in 2016-17 data, they were dead by then, and even if the core kept is the 2010 one, we should be cautious with those last years of measurements. 
@teixeirak , do you agree with this?

### second issue: There is one tag : 140820 that does not occur in any of the measurement notes files. 
 so its status.at.coring is blank. This I think is likely due to typo in the tag. This needs to be fixed. I (@ValentineHerr) think I can do it.

### third issue: the cores separated between live vs dead [in the climate_sensitivity_cores repository](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/tree/master/data/cores/live_vs_dead) are given their grouping potentially differently than above...
Dead or live is based on [census_data_for_cored_trees.csv](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/master/data/census_data_for_cored_trees.csv),  itself created by [this script](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/master/scripts/5-Pull_out_and_map_census_data_for_cored_trees.R)
That script is also giving precedence to notes in 2010 so a tag present in both measurement notes files would get "alive" instead of "dead" but that script does check that there is no overlap of tags in both measurement files and reports no issues. 
I (@ValentineHerr) need to check why that is.

**Comment by teixeirak** [comment]
> ### First issue: 29 tags appear in both measurement files.
> 
> In theory when a tree was cored a second time in 2016-17, that later core was used instead of the 2010 core. That means that those 29 tags should get a 'dead' status.at.coring instead of 'alive'.
> 
> In practice, 17 out of those 29 trees seem to have sopped before 2011 (sometimes much earlier) and 12 actually have data passed 2011. So it is unclear if those 17 trees should get 'dead' as the cores kept might well have been the 2010 core. Regardless, since we are removing the 10 years prior to death, we should probably change all those status to dead. Since the tags appear in 2016-17 data, they were dead by then, and even if the core kept is the 2010 one, we should be cautious with those last years of measurements.
> @teixeirak , do you agree with this?

First, I now forget whether we went with the tree cored later or the one with the longer record. I'm pretty sure that we can identify them based on the code: any cored dead should have the 'A' appended to the tag#. If not, the answer should be somewhere in our archives, but I'm not sure it matters so long as we have the tree data.

If we can sort it out easily, I'd actually tag them as alive if we're using the live core. The motivation is that we can't do something parallel at other sites, and removing trees that died after coring would bias the randomly selected set of living trees.

**Comment by ValentineHerr** [comment]
Ok @teixeirak, I'll look into the 'A' and let you know what I find (probably tomorrow)

I fixed issue 2

Issue 3 turns out to be poor coding on my part... the error that was supposed to show up when a tag was in both measurement note files would never show up... At least now I understand what was going on. It was not making sense otherwise.
So that means that the cores that are separated between live and dead in the climate_sensitivity_cores analysis suffer the same issue as the 29 tags mentioned in first issue.

**Comment by teixeirak** [comment]
> So that means that the cores that are separated between live and dead in the climate_sensitivity_cores analysis suffer the same issue as the 29 tags mentioned in first issue.

That's okay; we didn't use the live/dead distinction in the paper.

**Comment by ValentineHerr** [comment]
@teixeirak,

Last table below are the coreIDs that are from trees appearing in both measurement note files. Some have an "A" others don't. I also give the last year of core measurements:

I think it is fair to say that if there is an "A" it was cored dead. but there is a few ambiguous cases:

coreID|last meas year
--|--
030525A|2008
080479A|2007
162458r|2013
172218Ar|2009

What do you think? Here is the complete list.
coreID|last meas year
--|--
030525A|2008
080479A|2007
10539|2009
110920|2009
110952|2009
12080A|2016
121310|2009
122275|2009
131183A|2015
132010A|2015
151120|2009
152053A|2015
152659|2006
162458r|2013
172218Ar|2009
190830|2009
190929A|2015
192707|2009
202528A|2011
20605A|2014
40853A|2016
40952A|2017
42304|2009
50434|2006
60060|2007
70602|2009
70622A|2013
72361A|2016
80465r|2003

**Comment by teixeirak** [comment]
@ValentineHerr , sorry for the slow response. Any with an A were cored dead. Sometimes the outer rings were lost because of decay or breakage, and I'd assume that's what happened on the first 4.

**Comment by ValentineHerr** [comment]
OK, @teixeirak, I'll change Ian's script to give "dead" over "alive" for those cores with an 'A" and 'alive for others.

What about the 'r'? same as 'A'?

**Comment by teixeirak** [comment]
No, r means remeasured. Just disregard.

**Comment by ValentineHerr** [comment]
Then the rule of giving "dead" only to the ones with "A" does not work with 162458r which ends in 2013

**Comment by teixeirak** [comment]
That one must be an error. Let’s treat any with an r that go beyond 2010 as cores dead.

**Comment by ValentineHerr** [comment]
All right, I fixed that (see new table below) but now we have a new issue for 13 trees that I'll put in next comment

coreID|last meas year|status.at.coring
--|--|--
030525A|2008|dead
080479A|2007|dead
10539|2009|alive
110920|2009|alive
110952|2009|alive
12080A|2016|dead
121310|2009|alive
122275|2009|alive
131183A|2015|dead
132010A|2015|dead
151120|2009|alive
152053A|2015|dead
152659|2006|alive
162458r|2013|dead
172218Ar|2009|dead
190830|2009|alive
190929A|2015|dead
192707|2009|alive
202528A|2011|dead
20605A|2014|dead
40853A|2016|dead
40952A|2017|dead
42304|2009|alive
50434|2006|alive
60060|2007|alive
70602|2009|alive
70622A|2013|dead
72361A|2016|dead
80465r|2003|alive

**Comment by ValentineHerr** [comment]
now we have a new set of issues with trees that are in 2010 notes and not in 2016 notes, but have an "A" or have data passed 2010.

coreID|last meas year
--|--
101075|2011
111173|2017
111190A|2009
121434|2016
12445A|2009
202324|2012
40024A|2009
60550A|2009
80402A|2009
80437|2012
80640A|2006
92250A|2010
92486A|2009

**Comment by ValentineHerr** [comment]
@teixeirak what to do with those?

**Comment by teixeirak** [comment]
@ValentineHerr, I'm not sure. Perhaps @RHelcoski can help us understand what's going on.

**Comment by RHelcoski** [comment]
There are two reasons a tree could have an "A".

1) Trees cored in 2016/17. We took a core from the base (B) and dbh (A). I don't know why those two letters were chosen, but that was set up before me and I just went with it. 
2) Trees cored 2010 when a second core was taken from the same tree were labeled as "A" Any core from 2010 with an "A" was a second core used to replace an earlier core.

That leaves us with just 5 errors. The trees that end in 2011 and 2012 are almost definitely a mistake where the last "years" were layers of bark that were mistakenly measured. You could potentially just remove those years, since the rest of their data should be sound. But I would strongly recommend reviewing the files and the physical cores.

That leaves just one core that should definitely be physically checked and possibly removed. I don't know what's going on with 111173.

**Comment by teixeirak** [comment]
Many thanks, Ryan.

I'm afraid I don't understand this statement:
>     2\. Trees cored 2010 when a second core was taken from the same tree were labeled as "A" Any core from 2010 with an "A" was a second core used to replace an earlier core.

Does it mean thatJenny's convention was to add an A to a second core? So if tree 92250 was cored twice, those are labeled 92250 and 92250A? If so, that changes my answer to @ValentineHerr's question above. 

Well, there's no physical review of cores at the moment... One way to tell would be to check the mortality census data too see which trees died and were cored.

**Comment by RHelcoski** [comment]
Yes, that's what it means, sorry I wasn't clear. 

I completely forgot the physical cores can't be checked right now, haha. I believe all of those trees were indeed cored in 2010 except for the one I mentioned above.

**Comment by teixeirak** [comment]
Thanks!
@ValentineHerr , let's check any ambiguous ones in the 2017 mort files.

**Comment by ValentineHerr** [comment]
I checked all the tags listed in the table above and all but 80437 are alive in 2017.
80437 was 'DS' in 2013... so a best guess would be that it was dying when it was cored in 2010?

That means that 111173 was cored alive in 2010... and has 7 years of the bark counted? that seems a lot... but maybe not for a qupr?

**Comment by RHelcoski** [comment]
You're probably correct about 80437.

I don't know what's going on with 111173. 7 years is A LOT of bark counted even for qupr and even if it was putting on very small rings towards the end. Something is wrong, but I don't know what. It could be a minor typo made in 2010 that I didn't catch, it could be that in the initial counting there were numerous years that weren't really years at all (when the years are mm thick some people over or under count them) and it threw off the program building the chronology so it just stuck it where it made the most sense and Alan and I and Neil missed it. I honestly don't know. Ideally we would need to remeasure it and compare that to the original files and figure out what's going on. Maybe realistically all we can do is throw it out.

**Comment by teixeirak** [comment]
I'd agree on throwing it out, along with any other cores that are problematic. We're obviously not able to go back and remeasure cores right now.

**Comment by ValentineHerr** [comment]
@teixeira,
>along with any other cores that are problematic

Do you mean any core that seems to have been cored in 2010 but have data later than that?
Other option would be to delete any year >2010.

**Comment by teixeirak** [comment]
How many of those are there?

**Comment by ValentineHerr** [comment]
there is 5 cores that were supposedly cored in 2010 but have a measurement in 2011 or later.

**Comment by teixeirak** [comment]
Let's just throw those out. The ideal would be to go back and revisit the cores, but that's not feasible now.

Does that fully resolve this issue?

**Comment by ValentineHerr** [comment]
Thanks, yes I think so, but please review below - especially 3- and close this issue if you are happy with it. After this  I'll be able to finish preparing that template file in the dendro repo.

This is now how we are assigning "dead" or "alive", since we can't rely on the "A" anymore:
1. trees cored ONLY in 2010 --> "alive"
2. trees cored ONLY in 2016 --> "dead"
3. trees cored in BOTH 2010 and 2016 --> "dead" (with the idea that even if it was cored in 2010, it was a dying tree and we should delete the last 10 years of record), is that OK?
4. Delete any core that is "alive" but have data in 2011. (that is, 5 cores)

**Comment by teixeirak** [comment]
Sounds good, thanks.
