### ISSUE TITLE
sp codes in full plant list?

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/SCBI-ForestGEO-Data#24]
Hi @gonzalezeb 

I'm currently looking at [tree cores data](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/cross-dated_cores_CSVformat/all_core_chronologies.csv), which includes species codes `sp`. I'm still learning all the mappings from `sp` to scientific names,  common names, etc. I then found this very helpful [full plant list](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/species_lists/Full%20plant%20list/SCBI_all_sp_woody_%26_herb.csv) of all plant species. Questions:

1. Would you say that this list acts as a "master" florae species list for all SCBI databases?
1. If so, would you be open to a pull request where I add a fifth column called `sp` with species code? That way other forest ecology novices could do a quick join with the above list along the key variable `sp`. No problem if this doesn't fit into your plans.
1. The rule for creating `sp` codes seems simple enough: take the first two letters of both the genus and specific and paste them together with no space. However I noticed that *Carya ovalis* is coded as `caovl` instead of `caov`. At first I thought it was because more than one species could be coded as `caov` using the above rule, but that doesn't seem to be the case. Out of curiosity, could you explain why?

Many thanks

**Comment by gonzalezeb** [comment]
Albert, here your answers:
1. yes, this is the master plant species for the plot but notice that it also include herbaceous/ferns plants. For now, the sp codes only applies for woody species that are part of the census (what we also call "core census"). 
2. yes, I like that idea actually, but the more plants you have on that list the chances area that a code will repeat. We don't want that to affect our sp codes that have been used for years for analysis, etc. It is better that you use [this species list](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_main_census/data/census-csv-files/scbi.spptable.csv) for everything related to the forestgeo tree data at scbi.
3. no answer for that, that code was already given when I started to work at scbi. I never worried to changed, it should remain as it (at least for now).

Hope this help.

**Comment by rudeboybert** [comment]
Thanks for the info!
