### ISSUE TITLE
Review Mortality 2020 data

### ISSUE THREAD

**Issue by gonzalezeb** [SCBI-ForestGEO/SCBI-ForestGEO-Data#26]
Hi @camerondow35, this is for you to review..let me know if you have questions..

Problems founds in [Mortality_Survey_2020_csv](https://raw.githubusercontent.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/master/tree_mortality/raw%20data/Mortality_Survey_2020.csv)

- [x] More than 1800 records have no date or surveyor
- [x] Tag 30001: was DC in 2019, now is DS. It has same comment as last year. Should be PD. Tag 12271, was DS last year. Should be PD
- [x] Why some NOT Fraxinus trees that are Alive have ‘crown.position’ information? Multiples species have that info, in total 22 trees, why?.
- [x] Frpe 123412 and fram 133706 are missing crown.position
- [x] For some comments you wrote XX% whitening? What does it mean “whitening”? getting white? I have no idea what it means.

Others:
After all coring is done you need to indicate in the datasheet if ‘cored’=yes or no (column AE). 

About [data ](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_mortality/data)folder:
All files produced with the r script [1-Creating_data_files_from_raw_data.R](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_mortality/R_script/1-Creating_data_files_from_raw_data.R), have same length (13370 observations) but mortality_2020 has 72555 obs. Please check the code, there must be something wrong there..

**Comment by camerondow35** [comment]
> More than 1800 records have no date or surveyor

The only records w/o dates are PD, am I supposed to put a date for those too?

> Tag 30001: was DC in 2019, now is DS. It has same comment as last year. Should be PD. Tag 12271, was DS last year. Should be PD

Mistakes - fixed.

> Why some NOT Fraxinus trees that are Alive have ‘crown.position’ information? Multiples species have that info, in total 22 trees, why?.

Ah, they were AU last year and I forgot to delete the crown position. Fixed. 

> Frpe 123412 and fram 133706 are missing crown.position

Judging by dbh 2018 and quadrats they were in, I assigned them both S

> For some comments you wrote XX% whitening? What does it mean “whitening”? getting white? I have no idea what it means.

% whiteneing refers to EAB whitening. It's the same comments Alyssa used last year. Remove?

**Comment by camerondow35** [comment]
> About data folder:
All files produced with the r script 1-Creating_data_files_from_raw_data.R, have same length (13370 observations) but mortality_2020 has 72555 obs. Please check the code, there must be something wrong there..

For some reason all of mine had 75526...I'll try rerunning the script now that theyre reverted to the originals but there were parts of it I don't understand

**Comment by camerondow35** [comment]
Ran the script and pushed the result. Now has 13380...

**Comment by gonzalezeb** [comment]
answers to your questions @camerondow35 
> More than 1800 records have no date or surveyor
>The only records w/o dates are PD, am I supposed to put a date for those too?

Yes, they should have the same date when you visit that quadrat. 

>For some comments you wrote XX% whitening? What does it mean “whitening”? getting white? I have no idea what it means.
% whiteneing refers to EAB whitening. It's the same comments Alyssa used last year. Remove?

That term "EAB whitening" is not in the literature. What does it means to you? I think Alyssa meant  "20% bark flaking" . When the bark is removed by woodpeckers on a damaged tree (while searching for EAB larvae) the inner bark will get lighter. I think that's the reason why she came with that term. But we don't have to repeat it.  Tell me what did you mean with that and then we can make a decision to change the term in 2020.

**Comment by camerondow35** [comment]
OK would you like me to add dates based on the quadrat survey date or shall I just add one date for all PD? 

Yes, whitening refers to the EAB code W: bark blonding. I see in 2018 % was not noted in cases of W. I feel like 'whitening' is intuitive to me, since the code is a W. It might be confusing to use whitening for 2019 then change it in 2020, no?

**Comment by gonzalezeb** [comment]
>OK would you like me to add dates based on the quadrat survey date or shall I just add one date for all PD?

 they should have the same date when you visit that quadrat (based on the quadrat survey date)

>Yes, whitening refers to the EAB code W: bark blonding. I see in 2018 % was not noted in cases of W. I feel like 'whitening' is intuitive to me, since the code is a W. It might be confusing to use whitening for 2019 then change it in 2020, no?

Nope. Whitening is not a term related to EAB infection, and the 'W" was establish to refere to "Woodpecker" not "whitening" so let's don't repeat the mistake as 2019. Please replace by bark blonding in your comments.

**Comment by camerondow35** [comment]
> Nope. Whitening is not a term related to EAB infection, and the 'W" was establish to refere to "Woodpecker" not "whitening" so let's don't repeat the mistake as 2019. Please replace by bark blonding in your comments.

Should I replace it in 2019 as well, while im at it?

**Comment by camerondow35** [comment]
For the dates I just used this code `for(i in 1:nrow(Mortality_Survey_2020)){
Mortality_Survey_2020[i,32] <- ifelse(is.na(Mortality_Survey_2020[i,32]), Mortality_Survey_2020[(i-1),32], Mortality_Survey_2020[i,32])
}`
While likely not 100% accurate, i think this is the most efficient way of doing it.

**Comment by gonzalezeb** [comment]
sure for both

**Comment by camerondow35** [comment]
ok, pushed to github.
