### ISSUE TITLE
review/update mortality census protocol according to Arellano et al. 2021 

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-ForestGEO-Data#27]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/6355854/106150422-574b6d80-6149-11eb-87db-e0e6d6cafde1.png">

DOI: 10.1111/jvs.12981

**Comment by ValentineHerr** [comment]
@teixeirak Can we close this?

**Comment by teixeirak** [comment]
Yes, our new protocol does that!
