### ISSUE TITLE
sp mismatch between cores data & census data

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/SCBI-ForestGEO-Data#28]
For 63 tags/stemID's, the sp in the cores data does not match the sp in the census data. Of these, 60/63 are due to QUPR being renamed QUMO. The remaining three are less obvious (see table below). Here is a reproducible example.

```r
library(tidyverse)
library(lubridate)
library(here)

stemIDs_with_diff_sp <-
  c(1664, 1669, 3062, 3095, 3616, 4267, 5006, 5015, 5340, 5873,
    6210, 6252, 6317, 6873, 7009, 7034, 7188, 7327, 7341, 7949, 8114,
    8168, 8217, 8316, 8341, 8447, 9001, 9315, 9478, 9513, 9534, 9541,
    9735, 10897, 11059, 12565, 12695, 12740, 14519, 14520, 14537,
    14586, 19555, 19804, 20516, 20533, 21643, 21806, 21826, 23385,
    23754, 23777, 25801, 28491, 28493, 28497, 28506, 28529, 28550,
    30488, 30520, 30609, 30697)

# Load all cores data
cores <-
  "https://raw.githubusercontent.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/master/tree_cores/cross-dated_cores_CSVformat/all_core_chronologies.csv" %>%
  read_csv() %>%
  select(tag, cores_sp = sp) %>%
  arrange(tag)

# Load all census data
census <- bind_rows(
  "https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/raw/master/tree_main_census/data/census-csv-files/scbi.stem1.csv" %>%
    read_csv() %>%
    select(stemID, tag, sp, dbh) %>%
    mutate(year = 2008),
  "https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/raw/master/tree_main_census/data/census-csv-files/scbi.stem2.csv" %>%
    read_csv() %>%
    select(stemID, tag, sp, dbh) %>%
    mutate(year = 2013),
  "https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/raw/master/tree_main_census/data/census-csv-files/scbi.stem3.csv" %>%
    read_csv() %>%
    select(stemID, tag, sp, dbh) %>%
    mutate(year = 2018, dbh = as.numeric(dbh))
) %>%
  pivot_wider(id_cols = c(stemID, sp, tag), names_from = year, names_prefix = "census_", values_from = dbh) %>%
  arrange(stemID) %>%
  filter(stemID %in% stemIDs_with_diff_sp) %>%
  select(tag, stemID, census_sp = sp)


# Compare sp in cores and census data for these stemIDs
cores_mismatch <- left_join(census, cores, by = "tag") %>%
  arrange(cores_sp, tag)
cores_mismatch
```

|    tag| stemID|census_sp |cores_sp |
|------:|------:|:---------|:--------|
|  91391|  11059|cato      |cagl     |
| 111190|  14537|caco      |caovl    |
|  40873|   5340|quve      |fagr     |
|  10726|   1664|qupr      |qumo     |
|  10731|   1669|qupr      |qumo     |
|  22031|   3062|qupr      |qumo     |
|  22064|   3095|qupr      |qumo     |
|  22600|   3616|qupr      |qumo     |
|  32032|   4267|qupr      |qumo     |
|  40529|   5006|qupr      |qumo     |
|  40538|   5015|qupr      |qumo     |
|  42389|   5873|qupr      |qumo     |
|  50323|   6210|qupr      |qumo     |
|  50367|   6252|qupr      |qumo     |
|  50434|   6317|qupr      |qumo     |
|  52323|   6873|qupr      |qumo     |
|  52462|   7009|qupr      |qumo     |
|  60023|   7034|qupr      |qumo     |
|  60187|   7188|qupr      |qumo     |
|  60333|   7327|qupr      |qumo     |
|  60348|   7341|qupr      |qumo     |
|  62373|   7949|qupr      |qumo     |
|  70083|   8114|qupr      |qumo     |
|  70148|   8168|qupr      |qumo     |
|  70198|   8217|qupr      |qumo     |
|  70308|   8316|qupr      |qumo     |
|  70334|   8341|qupr      |qumo     |
|  70444|   8447|qupr      |qumo     |
|  72361|   9001|qupr      |qumo     |
|  80230|   9315|qupr      |qumo     |
|  80402|   9478|qupr      |qumo     |
|  80437|   9513|qupr      |qumo     |
|  80458|   9534|qupr      |qumo     |
|  80465|   9541|qupr      |qumo     |
|  80663|   9735|qupr      |qumo     |
|  90653|  10897|qupr      |qumo     |
| 100942|  12565|qupr      |qumo     |
| 101075|  12695|qupr      |qumo     |
| 101121|  12740|qupr      |qumo     |
| 111172|  14519|qupr      |qumo     |
| 111173|  14520|qupr      |qumo     |
| 111240|  14586|qupr      |qumo     |
| 140764|  19555|qupr      |qumo     |
| 141031|  19804|qupr      |qumo     |
| 142583|  20516|qupr      |qumo     |
| 142602|  20533|qupr      |qumo     |
| 151120|  21643|qupr      |qumo     |
| 152044|  21806|qupr      |qumo     |
| 152069|  21826|qupr      |qumo     |
| 162030|  23385|qupr      |qumo     |
| 162415|  23754|qupr      |qumo     |
| 162438|  23777|qupr      |qumo     |
| 172517|  25801|qupr      |qumo     |
| 192068|  28491|qupr      |qumo     |
| 192070|  28493|qupr      |qumo     |
| 192074|  28497|qupr      |qumo     |
| 192083|  28506|qupr      |qumo     |
| 192108|  28529|qupr      |qumo     |
| 192130|  28550|qupr      |qumo     |
| 202103|  30488|qupr      |qumo     |
| 202135|  30520|qupr      |qumo     |
| 202230|  30609|qupr      |qumo     |
| 202324|  30697|qupr      |qumo     |

**Comment by ValentineHerr** [comment]
@jess-shue, do you remember if you checked those trees back in May? (Mostly the 3 tricky ones at the top of the lists)? You had mentioned you would [here](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/issues/35#issuecomment-1118933569).
No worries at all if you didn't. I am just going through issues.

If you didn't, I think we can close this without doing anything because I trust the census data more than the core data (I don't know how the species were assigned to the trees that were cored). And also, because the new census will probably see if the wrong species were assigned.

**Comment by jess-shue** [comment]
@ValentineHerr Unfortunately, it looks like I made the file but wasn't able to get to those the first time around, and had since forgotten! I think we could even make a note on certain trees if the species should be checked during the census...I may not make that a priority for now, but it is a possibility.

**Comment by ValentineHerr** [comment]
no worries @jess-shue.
I'll have a paper list written next to the tablets, so the crew has those tags in mind to check!
