### ISSUE TITLE
Canopy position script

### ISSUE THREAD

**Issue by gonzalezeb** [SCBI-ForestGEO/SCBI-ForestGEO-Data#3]
What is the purpose of this script [canopy.position](https://github.com/SCBI-ForestGEO/Dendrobands/tree/master/Rscripts/canopy_position)?

**Comment by mcgregorian1** [comment]
This is a template script for my analysis, to compare crown position with trees bigger/smaller than 35cm dbh and comparing trees by canopy position (dominant/codominant; intermediate/suppressed).

I'll clarify this in the script

**Comment by mcgregorian1** [comment]
I've updated the filename to be more representative of what's in the file.
