### ISSUE TITLE
Question for which cores to use

### ISSUE THREAD

**Issue by mcgregorian1** [SCBI-ForestGEO/SCBI-ForestGEO-Data#4]
1. The [graph](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_dimensions/tree_crowns) in the pdf has been updated to include both alive trees and dead trees that were recorded as having a dbh > 0 in this past census.

- Question
- we have crown position data for some trees whose dbh2018 = 0 (in the graph, this is the furthest left column). It's kind of interesting in that it shows the crown positions for trees that died between 2013 and 2018.
- However, ultimately these have all fallen or the bark is peeled off. Do you want to keep these for the analysis?

2. You asked me to make a table of the number of cored trees by crown class. To do this, I simply need to find the tag numbers of cored trees and make a subset of our dendro_cored_full.

- Question
- the graph includes all records of cored trees from current_chronologies. According to Ryan’s [updated metadata](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data_private/tree/master/tree_cores/chronologies), however, he suggests only using “complete” chronologies for any analysis (based on [this list](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data_private/blob/master/tree_cores/chronologies/chronology_list.csv)). This would take out ~ 143 trees from our current graph, and reduce the number of species from 24 to 14. 
- Do we want to make this change? This would make our analysis be using the same cores Valentine used in running her code.

**Comment by teixeirak** [comment]
1. I'm confused as to when these trees with zero dbh died/ why they got canopy position but not DBH recorded. We must have a past dbh for them, and that can be used in place of dbh=0.
2. Yes, please do make that change-- for this particular analysis, where we're only interested in classifying the cores that can be used for your analysis. It will also be valuable to put all data into constructing a model to predict most likely canopy position by DBH and maybe species (as AJ  is working on), but that won't be needed for your analysis.

**Comment by mcgregorian1** [comment]
1. Yes, we have the dbh from the 2013 census; we recorded them dead in this year's census. I can assign them the 2013 dbh then.

2. Sounds good; I can do this.

**Comment by mcgregorian1** [comment]
@RHelcoski I'm tagging you just so you're aware.

@teixeirak 
I'm going through to complete step 2 (above), and I noticed there were some duplicates in the cores we used for Ryan's analysis. Specifically, the following:

90552 - it is in both cato and caovl chronologies. In 2018 census it is set as caovl. I've compared the two chronologies, and since they are identical, I've deleted the data from cato.

30567 - there is both an A and B cagl chronology. I'm noting this because this was still included in the cores run for Ryan's analysis, though I thought you had only wanted to process the A cores (according to Ryan's new metadata)? I'm assuming for my analysis when sending to Neil I'd only send the A chronology?
- should this is be fixed for Valentine's code to run on again?

172210 - cagl same thing as for 30567 above
92183 - cagl same thing as for 30567 above

### small fix
Ryan - in chronology_list, the "num_individual" column is sometimes right and sometimes a little off, based on the rows in the the csv files in [current_chronologies](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data_private/tree/master/tree_cores/chronologies/current_chronologies). I'm going through and fixing those numbers for all of them.

### current status
The graphs are updated to include only the specific individuals that were included in Ryan's analysis. Next step is to assign the numbers per canopy class.

An explanation of the different subsetting done to get the graphs is included as "DBH_CrownPosition_description.md" in the [tree_crowns](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_dimensions/tree_crowns) folder.

**Comment by RHelcoski** [comment]
Hey Ian, these were all changes that were made previously. Are you sure you didn't make edits to archived files?  (The small fixings)

**Comment by RHelcoski** [comment]
I'm referring to this section:
"90552 - it is in both cato and caovl chronologies. In 2018 census it is set as caovl. I've compared the two chronologies, and since they are identical, I've deleted the data from cato.

30567 - there is both an A and B cagl chronology. I'm noting this because this was still included in the cores run for Ryan's analysis, though I thought you had only wanted to process the A cores (according to Ryan's new metadata)? I'm assuming for my analysis when sending to Neil I'd only send the A chronology?

should this is be fixed for Valentine's code to run on again?
172210 - cagl same thing as for 30567 above
92183 - cagl same thing as for 30567 above"

**Comment by RHelcoski** [comment]
Check \Dropbox (Smithsonian)\climate sensitivity\results\z_FinalChronologies, these are the actual files that Valentine used and I don't see any B cores nor do I see the core issues you mentioned

**Comment by teixeirak** [comment]
I'm very glad to hear this! Let's replace the final chronologies in this repository with the correct one.

**Comment by mcgregorian1** [comment]
Ok, sounds good. I'll just update the rwl and csv files in current_chronologies. Thanks Ryan!

**Comment by RHelcoski** [comment]
No problem, I'm glad you tagged me. It can get complicated with so many versions of this data floating around.

**Comment by mcgregorian1** [comment]
@teixeirak everything is uploaded to github (along with a clearer graph) [here](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_dimensions/tree_crowns)

**Comment by mcgregorian1** [comment]
I think things are fine with this issue, so I'm going to close it.
