### ISSUE TITLE
Where to put spatial files?

### ISSUE THREAD

**Issue by mcgregorian1** [SCBI-ForestGEO/SCBI-ForestGEO-Data#5]
We currently have all our spatial data files for the plot (e.g. SCBI roads, streams, etc) in the V drive. I'd like to put them on Github, especially as the V drive is filled with different versions of the same data, when in reality we only need a few for the plot.

Would it be better to add those shapefiles in a public or private repo?

The shapefiles I'd move over are:

- roads
- streams
- plot grid
- deer exclosure
- 10m contour
- biannual survey areas
- N/S divider line for intraannual surveys

**Comment by teixeirak** [comment]
The first 5 should all be public (and that will be very helpful!). The latter two may be better in the dendro band folder.

**Comment by mcgregorian1** [comment]
@teixeirak sounds good. The latter two are now in the [denrobands folder](https://github.com/SCBI-ForestGEO/Dendrobands/tree/master/resources/maps/shapefiles) whereas the first five are in [SCBI-ForestGEO-Data](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/spatial_data).

**Comment by teixeirak** [comment]
Thanks!

**Comment by mcgregorian1** [comment]
For the record, I added the scripts for converting plot coordinates to lat/long. They are located with the other general shapefiles for the forestgeo plot

**Comment by gonzalezeb** [comment]
@mcgregorian1 
These R scrips have almost the same information so please combine them and keep only one. 
Also move the script to the R script folder (since all files in the spatial folder are shape files). 
When you combine the scrips, I will make some minor modifications. Thanks!

**Comment by mcgregorian1** [comment]
@gonzalezeb it's done, and I've put it in the scripts folder.

I quickly went through the script and I noticed these two lines, which I think in the one you edited in January you removed the "20*" from the code. 

Here's your edit:
`## get grid coordinates by multiplying each quadrat coordinate by 20 and adding the corresponding within-quadrat coordinate (lx and ly)`
`sigeo$grid_x <- (sigeo$quadrat_x - 1)`
`sigeo$grid_y <- (sigeo$quadrat_y - 1)`

And here's the original code. I wasn't sure what the original code was trying to do.
`## get grid coordinates by multiplying each quadrat coordinate by 20 and adding the corresponding within-quadrat coordinate (lx and ly)`
`sigeo$grid_x <- 20 * (sigeo$quadrat_x - 1`
`sigeo$grid_y <- 20 * (sigeo$quadrat_y - 1) + sigeo$ly`

**Comment by mcgregorian1** [comment]
Also so it's known: to make a plot map based on lat/lon coordinates in R (and spatially projected correctly), the code Valentine and I made with ggplot (in [survey_maps](https://github.com/SCBI-ForestGEO/Dendrobands/tree/master/Rscripts/survey_forms)) for dendrobands can easily be used; we just have to specify the data as being the output from this conversion script.
